<?php

namespace Proxies\__CG__\GSB\AndroidBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Praticien extends \GSB\AndroidBundle\Entity\Praticien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praNum', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praNom', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praPrenom', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praAdresse', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praCp', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praVille', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praCoefnotoriete', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'typCode', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'acNum', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'speCode');
        }

        return array('__isInitialized__', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praNum', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praNom', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praPrenom', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praAdresse', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praCp', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praVille', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'praCoefnotoriete', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'typCode', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'acNum', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Praticien' . "\0" . 'speCode');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Praticien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPraNum()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPraNum();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraNum', array());

        return parent::getPraNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraNom($praNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraNom', array($praNom));

        return parent::setPraNom($praNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraNom', array());

        return parent::getPraNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraPrenom($praPrenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraPrenom', array($praPrenom));

        return parent::setPraPrenom($praPrenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraPrenom', array());

        return parent::getPraPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraAdresse($praAdresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraAdresse', array($praAdresse));

        return parent::setPraAdresse($praAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraAdresse', array());

        return parent::getPraAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraCp($praCp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraCp', array($praCp));

        return parent::setPraCp($praCp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraCp', array());

        return parent::getPraCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraVille($praVille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraVille', array($praVille));

        return parent::setPraVille($praVille);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraVille', array());

        return parent::getPraVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setPraCoefnotoriete($praCoefnotoriete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPraCoefnotoriete', array($praCoefnotoriete));

        return parent::setPraCoefnotoriete($praCoefnotoriete);
    }

    /**
     * {@inheritDoc}
     */
    public function getPraCoefnotoriete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPraCoefnotoriete', array());

        return parent::getPraCoefnotoriete();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypCode(\GSB\AndroidBundle\Entity\TypePraticien $typCode = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypCode', array($typCode));

        return parent::setTypCode($typCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypCode', array());

        return parent::getTypCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addAcNum(\GSB\AndroidBundle\Entity\ActiviteCompl $acNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAcNum', array($acNum));

        return parent::addAcNum($acNum);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAcNum(\GSB\AndroidBundle\Entity\ActiviteCompl $acNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAcNum', array($acNum));

        return parent::removeAcNum($acNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcNum', array());

        return parent::getAcNum();
    }

    /**
     * {@inheritDoc}
     */
    public function addSpeCode(\GSB\AndroidBundle\Entity\Specialite $speCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSpeCode', array($speCode));

        return parent::addSpeCode($speCode);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSpeCode(\GSB\AndroidBundle\Entity\Specialite $speCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSpeCode', array($speCode));

        return parent::removeSpeCode($speCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeCode', array());

        return parent::getSpeCode();
    }

}
