<?php

namespace Proxies\__CG__\GSB\AndroidBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Collaborateur extends \GSB\AndroidBundle\Entity\Collaborateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colMatricule', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colNom', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colMdp', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colPrenom', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colAdresse', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colCp', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colVille', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colDateembauche', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'labCode', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'secCode', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'acNum');
        }

        return array('__isInitialized__', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colMatricule', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colNom', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colMdp', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colPrenom', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colAdresse', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colCp', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colVille', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'colDateembauche', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'labCode', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'secCode', '' . "\0" . 'GSB\\AndroidBundle\\Entity\\Collaborateur' . "\0" . 'acNum');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Collaborateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getColMatricule()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getColMatricule();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColMatricule', array());

        return parent::getColMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setColNom($colNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColNom', array($colNom));

        return parent::setColNom($colNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getColNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColNom', array());

        return parent::getColNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setColMdp($colMdp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColMdp', array($colMdp));

        return parent::setColMdp($colMdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getColMdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColMdp', array());

        return parent::getColMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setColPrenom($colPrenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColPrenom', array($colPrenom));

        return parent::setColPrenom($colPrenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getColPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColPrenom', array());

        return parent::getColPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setColAdresse($colAdresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColAdresse', array($colAdresse));

        return parent::setColAdresse($colAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getColAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColAdresse', array());

        return parent::getColAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setColCp($colCp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColCp', array($colCp));

        return parent::setColCp($colCp);
    }

    /**
     * {@inheritDoc}
     */
    public function getColCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColCp', array());

        return parent::getColCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setColVille($colVille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColVille', array($colVille));

        return parent::setColVille($colVille);
    }

    /**
     * {@inheritDoc}
     */
    public function getColVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColVille', array());

        return parent::getColVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setColDateembauche($colDateembauche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColDateembauche', array($colDateembauche));

        return parent::setColDateembauche($colDateembauche);
    }

    /**
     * {@inheritDoc}
     */
    public function getColDateembauche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColDateembauche', array());

        return parent::getColDateembauche();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabCode(\GSB\AndroidBundle\Entity\Laboratoire $labCode = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabCode', array($labCode));

        return parent::setLabCode($labCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabCode', array());

        return parent::getLabCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecCode(\GSB\AndroidBundle\Entity\Secteur $secCode = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecCode', array($secCode));

        return parent::setSecCode($secCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecCode', array());

        return parent::getSecCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addAcNum(\GSB\AndroidBundle\Entity\ActiviteCompl $acNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAcNum', array($acNum));

        return parent::addAcNum($acNum);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAcNum(\GSB\AndroidBundle\Entity\ActiviteCompl $acNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAcNum', array($acNum));

        return parent::removeAcNum($acNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcNum', array());

        return parent::getAcNum();
    }

}
