<?php

namespace GSB\AndroidBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollaborateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravaillerRepository extends EntityRepository
{
}
