parameters:
#    gsb_android.example.class: GSB\AndroidBundle\Example

services:
#    gsb_android.example:
#        class: %gsb_android.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
